# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: ubuntu-latest
variables:
 resourceGroupName: "CONTAPP-APIM-DEV-1"
 testresourceGroupName: "CONTAPP-APIM-TEST-1"
 location: "eastus"
 APP_NAME: "mypoc"
 APP_ENV: "dev"
 APP_ENV_TEST: "test"

stages:
  - stage: Dev
    jobs:
      - deployment: Dev
        displayName: Create_Infra_Dev
        environment: dev
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: AzureCLI@2
                  inputs:
                    azureSubscription: 'masterconnection'
                    scriptType: 'bash'
                    scriptLocation: 'scriptPath'
                    scriptPath: 'Infrastructure/Platform/create-infra.sh'
                  env:
                    appname: $(APP_NAME)
                    appEnv: $(APP_ENV)
                    resourceGroupName: $(resourceGroupName)
                    location: $(location)
  # - stage: Test
  #   jobs:
  #     - deployment: Test
  #       displayName: Create_Infra_Test
  #       environment: Test
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - checkout: self
  #               - task: AzureCLI@2
  #                 inputs:
  #                   azureSubscription: 'masterconnection'
  #                   scriptType: 'bash'
  #                   scriptLocation: 'scriptPath'
  #                   scriptPath: 'Infrastructure/Platform/create-infra.sh'
  #                 env:
  #                   appname: $(APP_NAME)
  #                   appEnv: $(APP_ENV_TEST)
  #                   resourceGroupName: $(testresourceGroupName)
  #                   location: $(location)                    


  
      

